#ifndef JXR_INVERSE_TRANSFORM_MATH_H
#define JXR_INVERSE_TRANSFORM_MATH_H

#include "windowsmediaphoto.h"

Void JxrInverseTransformMathRotateHalf(PixelI* first, PixelI* second);
Void JxrInverseTransformMathRotateThreeEighths(PixelI* first, PixelI* second);
Void JxrInverseTransformMathAddCornerPrediction(PixelI* target, PixelI prediction);
Void JxrInverseTransformMathSubtractCornerPrediction(PixelI* target, PixelI prediction);
Void JxrInverseTransformMathNormalizeBlock(
    PixelI* samples,
    Bool chroma,
    Int sampleCount,
    Int sampleStride);
Bool JxrInverseTransformMathShouldCompensateDc(
    Int directCurrent,
    Int highPassQuantizer,
    Bool highPassAbsent);
Void JxrInverseTransformMathApplyDcCompensation(
    PixelI* topLeft,
    PixelI* topRight,
    PixelI* bottomLeft,
    PixelI* bottomRight,
    Int directCurrent);
Int JxrInverseTransformMathClipDcWithAlternate(
    Int directCurrent,
    Int alternateCurrent);
Int JxrInverseTransformMathApplyConditionalDcCompensation(
    PixelI* topLeft,
    PixelI* topRight,
    PixelI* bottomLeft,
    PixelI* bottomRight,
    Int directCurrent,
    Int highPassQuantizer,
    Bool highPassAbsent);
Void JxrInverseTransformMathApplyPost4(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyAlternatePost4(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyHadamardScale4(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyHadamardScale2(
    PixelI* first,
    PixelI* second);
Void JxrInverseTransformMathApplyAlternateHadamardScale2(
    PixelI* first,
    PixelI* second);
Void JxrInverseTransformMathApplyOddOdd(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyOddOddPost(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyOdd(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyScaledDct2x2Down(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyPost2(
    PixelI* first,
    PixelI* second);
Void JxrInverseTransformMathApplyAlternatePost2(
    PixelI* first,
    PixelI* second);
Void JxrInverseTransformMathApplyPost2x2(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);
Void JxrInverseTransformMathApplyAlternatePost2x2(
    PixelI* first,
    PixelI* second,
    PixelI* third,
    PixelI* fourth);

#endif
